
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lzgnujlvtrfdaggdkjbc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6Z251amx2dHJmZGFnZ2RramJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4MzA1NTksImV4cCI6MjA1OTQwNjU1OX0._RxFN8C6HljpA-YHt5CUS4xIJijJPYaNluxuCUiDPtQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
